#!/usr/bin/env python3
"""
Treatment Plan Generator using MedGemma
Generates evidence-based treatment recommendations for medical cases using AI.

DISCLAIMER: This script generates AI-simulated treatment plans for research and 
educational purposes only. These are NOT real clinical recommendations and should 
never be used for actual patient care.
"""

import sys
from pathlib import Path

# Add local packages to path
local_lib = Path(__file__).parent / ".venv" / "lib"
if local_lib.exists():
    sys.path.insert(0, str(local_lib))

import json
import torch
from transformers import pipeline
from PIL import Image
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional
import logging
import re
import os

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('treatment_generation.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class TreatmentPlanGenerator:
    """Generate treatment plans using MedGemma model."""
    
    DISCLAIMER = (
        "This treatment plan was generated by AI for research/educational purposes only. "
        "It should NOT be used for actual clinical decision-making or patient care. "
        "Always consult qualified healthcare professionals for medical treatment."
    )
    
    def __init__(self, model_name: str = "google/medgemma-1.5-4b-it", device: str = "cuda"):
        """Initialize the MedGemma model."""
        logger.info(f"Loading MedGemma model: {model_name}")
        
        try:
            self.pipe = pipeline(
                "image-text-to-text",
                model=model_name,
                torch_dtype=torch.bfloat16,
                device=device,
            )
            logger.info("Model loaded successfully")
        except Exception as e:
            logger.error(f"Failed to load model: {e}")
            raise
        
        self.model_name = model_name
        self.device = device
    
    def build_treatment_prompt(self, case_data: Dict) -> str:
        """Build a detailed prompt for treatment plan generation."""
        
        patient = case_data.get('patient', {})
        presentation = case_data.get('presentation', {})
        assessment = case_data.get('assessment', {})
        findings = case_data.get('findings', {})
        
        # Extract patient information
        age = patient.get('age_years', 'unknown')
        sex = patient.get('sex', 'unknown')
        comorbidities = ', '.join(patient.get('comorbidities', [])) or 'none reported'
        current_meds = ', '.join(patient.get('medications', [])) or 'none reported'
        allergies = patient.get('allergies', 'none reported')
        
        # Extract clinical information
        diagnosis = assessment.get('diagnosis_primary', 'unknown')
        urgency = assessment.get('urgency', 'unknown')
        infectious = assessment.get('infectious_concern', 'unknown')
        icu_candidate = assessment.get('icu_candidate', 'unknown')
        
        # Build comprehensive prompt
        prompt = f"""As a medical expert, provide a detailed evidence-based treatment plan for the following case:

PATIENT DEMOGRAPHICS:
- Age: {age} years
- Sex: {sex}
- Comorbidities: {comorbidities}
- Current medications: {current_meds}
- Known allergies: {allergies}

CLINICAL PRESENTATION:
- Chief complaint: {presentation.get('chief_complaint', 'not specified')}
- Duration: {presentation.get('symptom_duration', 'not specified')}
- Clinical summary: {presentation.get('hpi', 'not specified')}

DIAGNOSIS:
- Primary diagnosis: {diagnosis}
- Urgency level: {urgency}
- Infectious concern: {infectious}
- ICU candidate: {icu_candidate}

IMAGING FINDINGS:
{self._format_findings(findings)}

You MUST provide the treatment plan strictly as a valid JSON object matching this schema. Do NOT include any markdown code blocks, explanatory text, or anything other than the JSON itself.

{{
  "medications": [
    {{
      "drug_name": "string",
      "dosage": "string",
      "route": "string",
      "frequency": "string",
      "duration": "string",
      "indication": "string"
    }}
  ],
  "imaging_followup": [
    {{
      "modality": "string",
      "body_region": "string",
      "timing": "string",
      "indication": "string"
    }}
  ],
  "procedures": [
    {{
      "procedure_name": "string",
      "urgency_level": "string",
      "indication": "string"
    }}
  ],
  "supportive_care": ["string"],
  "referrals": [
    {{
      "specialty": "string",
      "urgency": "string"
    }}
  ],
  "monitoring_parameters": [
    {{
      "parameter": "string",
      "frequency": "string"
    }}
  ]
}}"""

        return prompt
    
    def _format_findings(self, findings: Dict) -> str:
        """Format imaging findings for the prompt."""
        findings_text = []
        
        if 'lungs' in findings:
            lungs = findings['lungs']
            if lungs.get('consolidation_present') == 'yes':
                locations = ', '.join(lungs.get('consolidation_locations', []))
                findings_text.append(f"- Consolidation present in: {locations}")
            if lungs.get('atelectasis_present') == 'yes':
                findings_text.append("- Atelectasis noted")
            if lungs.get('edema_present') == 'yes':
                findings_text.append(f"- Pulmonary edema pattern: {lungs.get('edema_pattern', 'unspecified')}")
        
        if 'pleura' in findings:
            pleura = findings['pleura']
            if pleura.get('effusion_present') == 'yes':
                findings_text.append(f"- Pleural effusion ({pleura.get('effusion_side', 'unknown side')}, {pleura.get('effusion_size', 'unknown size')})")
            if pleura.get('pneumothorax_present') == 'yes':
                findings_text.append(f"- Pneumothorax ({pleura.get('pneumothorax_side', 'unknown side')})")
        
        if 'cardiomediastinal' in findings:
            cardio = findings['cardiomediastinal']
            if cardio.get('cardiomegaly') == 'yes':
                findings_text.append("- Cardiomegaly")
            if cardio.get('mediastinal_widening') == 'yes':
                findings_text.append("- Mediastinal widening")
        
        return '\n'.join(findings_text) if findings_text else "- No significant findings documented"
    
    def generate_treatment_plan(self, case_data: Dict, image_path: Optional[str] = None) -> Dict:
        """Generate treatment plan for a case."""
        
        logger.info(f"Generating treatment plan for case: {case_data.get('case_id', 'unknown')}")
        
        # Build prompt
        prompt = self.build_treatment_prompt(case_data)
        
        # Prepare messages
        messages = [{"role": "user", "content": []}]
        
        # Add image if available
        if image_path and os.path.exists(image_path):
            try:
                image = Image.open(image_path)
                messages[0]["content"].append({"type": "image", "image": image})
                logger.info(f"Added image: {image_path}")
            except Exception as e:
                logger.warning(f"Could not load image {image_path}: {e}")
        
        # Add text prompt
        messages[0]["content"].append({"type": "text", "text": prompt})
        
        # Generate response
        try:
            output = self.pipe(text=messages, max_new_tokens=4096)
            response_text = output[0]["generated_text"][-1]["content"]
            logger.info("Treatment plan generated successfully")
        except Exception as e:
            logger.error(f"Error generating treatment plan: {e}")
            raise
        
        # Parse response into structured format
        treatment_plan = self.parse_treatment_response(response_text)
        
        # Add metadata
        result = {
            "treatment_plan": treatment_plan,
            "generation_metadata": {
                "generated_by": self.model_name,
                "generation_date": datetime.now().isoformat(),
                "disclaimer": self.DISCLAIMER,
                "raw_response": response_text
            }
        }
        
        return result
    
    def parse_treatment_response(self, response: str) -> Dict:
        """Parse the model's response into structured JSON."""
        
        default_plan = {
            "medications": [],
            "imaging_followup": [],
            "procedures": [],
            "supportive_care": [],
            "referrals": [],
            "monitoring_parameters": [],
            "clinical_notes": response
        }
        
        try:
            # Clean special tokens before extracting
            json_str = response.replace('<unused94>', '').replace('<unused95>', '').strip()
            
            # Extract JSON block if surrounded by markdown
            match = re.search(r'```(?:json)?\s*(.*?)\s*```', json_str, re.DOTALL)
            if match:
                json_str = match.group(1).strip()
            else:
                # Find first { and last }
                start = json_str.find('{')
                end = json_str.rfind('}')
                if start != -1 and end != -1:
                    json_str = json_str[start:end+1]
            
            parsed = json.loads(json_str)
            
            # Merge with default plan to ensure all keys exist
            for key, val in default_plan.items():
                if key not in parsed:
                    parsed[key] = val
                    
            parsed["clinical_notes"] = response
            return parsed
            
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse JSON response: {e}. Returning raw response in clinical_notes.")
            return default_plan


def process_dataset(
    input_file: str,
    output_file: str,
    checkpoint_file: str = "treatment_checkpoint.json",
    start_index: int = 0,
    max_cases: Optional[int] = None
):
    """Process dataset and generate treatment plans."""
    
    logger.info(f"Loading dataset from {input_file}")
    
    # Load existing data
    with open(input_file, 'r') as f:
        cases = json.load(f)
    
    logger.info(f"Loaded {len(cases)} cases")
    
    # Load checkpoint if exists
    processed_ids = set()
    if os.path.exists(checkpoint_file):
        with open(checkpoint_file, 'r') as f:
            checkpoint = json.load(f)
            processed_ids = set(checkpoint.get('processed_ids', []))
            logger.info(f"Loaded checkpoint: {len(processed_ids)} cases already processed")
    
    # Initialize generator
    generator = TreatmentPlanGenerator()
    
    # Process cases
    updated_cases = []
    processed_count = 0
    
    for i, case in enumerate(cases):
        if max_cases and processed_count >= max_cases:
            logger.info(f"Reached max_cases limit: {max_cases}")
            break
        
        case_id = case.get('case_id', f'case_{i}')
        
        # Skip if already processed
        if case_id in processed_ids:
            updated_cases.append(case)
            continue
        
        if i < start_index:
            updated_cases.append(case)
            continue
        
        try:
            # Get image path if available
            image_path = None
            if 'study' in case and 'storage_path' in case['study']:
                base_dir = Path(input_file).parent.parent
                image_path = base_dir / case['study']['storage_path']
                if not image_path.exists():
                    image_path = None
            
            # Generate treatment plan
            treatment_data = generator.generate_treatment_plan(case, str(image_path) if image_path else None)
            
            # Add to case
            case['treatment_plan'] = treatment_data['treatment_plan']
            case['generation_metadata'] = treatment_data['generation_metadata']
            
            updated_cases.append(case)
            processed_ids.add(case_id)
            processed_count += 1
            
            logger.info(f"Processed {processed_count}/{len(cases)}: {case_id}")
            
            # Save checkpoint every 10 cases
            if processed_count % 10 == 0:
                with open(checkpoint_file, 'w') as f:
                    json.dump({
                        'processed_ids': list(processed_ids),
                        'last_processed_index': i
                    }, f)
                logger.info(f"Checkpoint saved at {processed_count} cases")
            
        except Exception as e:
            logger.error(f"Error processing case {case_id}: {e}")
            updated_cases.append(case)  # Add without treatment plan
            continue
    
    # Save final output
    logger.info(f"Saving results to {output_file}")
    with open(output_file, 'w') as f:
        json.dump(updated_cases, f, indent=2)
    
    logger.info(f"Processing complete! Generated {processed_count} treatment plans")


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate treatment plans for medical cases")
    parser.add_argument('--input', type=str, required=True, help='Input dataset JSON file')
    parser.add_argument('--output', type=str, required=True, help='Output dataset JSON file')
    parser.add_argument('--checkpoint', type=str, default='treatment_checkpoint.json', help='Checkpoint file')
    parser.add_argument('--start-index', type=int, default=0, help='Start processing from this index')
    parser.add_argument('--max-cases', type=int, default=None, help='Maximum number of cases to process')
    
    args = parser.parse_args()
    
    process_dataset(
        input_file=args.input,
        output_file=args.output,
        checkpoint_file=args.checkpoint,
        start_index=args.start_index,
        max_cases=args.max_cases
    )
